feature: Add docker-compose to flake / devShell
bitemyapp/bloodhound pull request #297
Opened 2024-10-17 08:29 UTC by supersven

`dockerd` relies on superuser/system access and thus should be provided by the operating system. However, `docker-compose` simply uses `dockerd` and thus can be part of the flake's dependencies for the `devShell`.

2024-10-19 16:41 UTC, blackheaven requested changes

2024-10-19 16:41 UTC, blackheaven commented on flake.nix
>                  ghcid
```suggestion
              buildInputs = with haskellPackages; [
                pkgs.docker-compose
                haskell-language-server
                ghcid
```

2024-10-19 16:41 UTC, blackheaven commented on flake.nix
> +              ]);
```suggestion
              ];
```

2024-10-20 08:32 UTC, supersven commented on flake.nix
> +              ]);
That should be fine as well :+1:

2024-10-20 16:35 UTC, blackheaven approved these changes

2024-10-20 16:36 UTC, merged

2024-10-20 16:39 UTC, blackheaven commented
Thanks for your contributions.